./1_prepare_build.sh                          
./2_1_get_freerdp.sh                                 
./2_2_build_freerdp.sh 
./3_1_get_ogon.sh
./3_2_build_ogon.sh
./3_3_install_openh364.sh
./3_4_install_ogon.sh
./4_1_get_apps.sh
./4_2_build_apps.sh
./5_1_get_platform_qt.sh 
./5_2_build_platform_qt.sh
./6_1_get_greeter_qt.sh
./6_2_build_greeter_qt.sh
./7_1_get_libxfont.sh
./7_2_build_libxfont.sh 
./8_1_get_xserver.sh       
./8_2_build_xserver.sh   
./9_1_get_deps_channels.sh
./9_2_get_channels.sh
./9_3_build_channels.sh
./10_1_get_deps_pulseaudio.sh 
./10_2_get_pulseaudio.sh
./10_3_build_pulseaudio.sh
./finalize.sh
